#!/usr/bin/env bash
set -e 

CONFIG_DIR=$1

/usr/sbin/sshd -e -D -p 10000 -h $CONFIG_DIR/signpost.pem \
    -o "AllowUsers=root" -o "PermitTunnel=yes" \
    -o "AuthorizedKeysFile=.ssh/signpost_tunnel" \
    -o "PermitRootLogin=yes" \
    -o "PidFile=/tmp/signpost_sshd.pid" \
    -f $CONFIG_DIR/sshd_config

