#!/usr/bin/env bash

set -e 

CONF_DIR=$1

/usr/sbin/sshd -p 10000 -e -h $CONF_DIR/id_rsa -o "AllowUsers=root" -o "PermitTunnel=yes" \
    -o "AuthorizedKeysFile=.ssh/signpost_tunnel" -o "PermitRootLogin=forced-commands-only" \
    -o "PidFile=/tmp/signpost_sshd.pid"
