#!/usr/bin/env bash
set -ex

NS="192.168.56.101"

PASS=`cat scripts/PASSWD`
if [ "`ps -e | grep iodine | wc -l `" -lt 2 ]; then
    iodine -r -P ${PASS} $NS i.d2.signpo.st;
fi

if [ "`ifconfig | grep -E "^tun0" | wc -l`" -gt 0 ]; then
    IP=`ifconfig tun0 |grep 172.16 | awk '{print $2}'`;
else
    if [ "`ifconfig | grep dns0 | wc -l`" -gt 0 ]; then 
        IP=`ifconfig dns0 |grep 172.16 | tr \: \  | awk '{print $3}'`;
    else
        echo "no valid network interface found"
        exit 1
    fi
fi
SIG_PORT=42425
./client.native `hostname -s` $IP $SIG_PORT
