#!/usr/bin/env bash
set -ex

NS=`cat lib/config.ml | grep external_ip | awk '{print $4}' | sed 's/"//g'`
IODINE_DOMAIN="i.d2.signpo.st"
NS="23.23.179.30"
#NODE_NAME=`hostname -s`
NODE_NAME=tablet

PASS=`cat scripts/PASSWD`
if [ "`ps -e | grep iodine | wc -l `" -lt 1 ]; then
  if [ $NS -eq "" ]; then
    iodine -P ${PASS} "$IODINE_DOMAIN";
  else
    iodine -P ${PASS} $NS "$IODINE_DOMAIN"
  fi
fi

if [ "`ifconfig | grep -E "^tun0" | wc -l`" -gt 0 ]; then
    IP=`ifconfig tun0 |grep 172.16 | awk '{print $2}'`;
else
    if [ "`ifconfig | grep dns0 | wc -l`" -gt 0 ]; then 
        IP=`ifconfig dns0 |grep 172.16 | tr \: \  | awk '{print $3}'`;
    else
        echo "no valid network interface found"
        exit 1
    fi
fi
SIG_PORT=42425

# delete all arp entries, so that we will discover them using openflow
arp -n | awk '/(^[0-9]+\.?)+/ {print $1;}' | xargs -I '{}' arp -d '{}'

ovs-dpctl show br0 | grep tap | awk '{print $3}' \
  | xargs -I '{}' ovs-dpctl del-if br0  '{}'
ip addr show  dev br0 | grep 10\\.2\\. | awk '{print $2;}' \
  |  xargs -I '{}'  ip addr del  '{}' dev br0

./client.native $NODE_NAME $IP $SIG_PORT
