#!/usr/bin/env bash
set -ex

d=$(dirname $(readlink -f $0))
if [ ! -e "${d}/PASSWD" ]; then
  echo Create file called PASSWD in ${d} containing your password
  exit 1
fi

IP_RANGE=`cat lib/config.ml | grep ip_slash_24 | awk '{print $4}' | sed 's/"//g'`
NUM=`cat lib/config.ml | grep signpost_number | awk '{print $4}'`
DOMAIN=`cat lib/config.ml | grep domain | awk '{print $4}' | sed 's/"//g'`

cd ${d}
PASS=`cat PASSWD`
if [ "`ps -e | grep iodined | wc -l `" -eq 0 ]; then
  echo "Setting up iodined"
  iodined -F /tmp/iodine.pid -P "${PASS}" -c -b 5354 "${IP_RANGE}1/24" i.d$NUM.$DOMAIN;
fi
../_build/lib/server.native
