#!/usr/bin/env bash 

# ip addr show | awk '/^[0-9]*:/ {dev=$2;sub(/\:/,"", dev);} /inet / {split($2,a,"/"); print dev,a[1];}'

ip addr show | awk '/^[0-9]*:/ {dev=$2;sub(/\:/,"", dev);mac="00:00:00:00:00"} /link\/ether/{mac=$2}  /inet / {split($2,a,"/"); print dev,a[1],mac;}'
