#! /usr/bin/env bash

# Copyright (c) 2012 Sebastian Probst Eide <sebastian.probst.eide@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.


set -e

function main {
  ifconfig -a | 
  sed -e "s/addr://g" |
  get_ipv4_addresses |
  exclude_local_addresses |
  exclude_signalling_channel_range |
  xargs
}

function exclude_signalling_channel_range {
  if [ -e lib/config.ml ]; then  
    signalling_channel_range=`cat lib/config.ml | grep ip_slash_24 | awk '{print $4}' | sed 's/"//g'`
  else 
    signalling_channel_range=`cat ../lib/config.ml | grep ip_slash_24 | awk '{print $4}' | sed 's/"//g'`
  fi
  grep -v -E "$signalling_channel_range"
}

function exclude_local_addresses {
  grep -v -E "(127\.0)"
}

function get_ipv4_addresses {
  grep inet | 
  grep -v inet6 | 
  awk '{print $2}' 
}

main;
